name: Solar System
on: push
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Clone The Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 

      - name: Install dependencies
        run: npm install
    
      - name: Install npm Test
        run: |
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV
            echo "MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}" >> $GITHUB_ENV
            echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> $GITHUB_ENV

      - name: Run tests
        run: npm test

  Container_Build:
    runs-on: ubuntu-latest
    needs: unit-testing
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Login To Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        id: build_Image
        with:
          load: true
          push: false
          tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-sys:latest
          
      - name: Test_Image
        if: steps.Build_Image == 'success'
        id: Test_Image
        run: |
            docker run -d --name solar-sys -e MONGO_URI=${{ secrets.MONGO_URI }} \
            -e MONGO_USERNAME=${{ secrets.MONGO_USERNAME }} \
            -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} -p 3000:3000 \
            ${{ vars.DOCKERHUB_USERNAME }}/solar-sys:latest 
            docker inspect solar-sys | grep -i ipaddress

      - name: Push Image
        uses: docker/build-push-action@v6
        if: steps.Test_Image == 'success'
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-sys:latest




